//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.20 at 06:00:42 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://uni-stuttgart.de/iev/osmosisTaskDescription", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.osmui.model.osm;
